In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.io as pio
pio.templates.default = "simple_white"

In [2]:
df = pd.read_csv(
    "https://raw.githubusercontent.com/bdi593/datasets/refs/heads/main/google-trends-celebrities/google-trends-celebrities.csv"
)

df

       datetime     keyword  trend_index
0      Jan 2004  Kanye West            7
1      Feb 2004  Kanye West           13
2      Mar 2004  Kanye West           15
3      Apr 2004  Kanye West           15
4      May 2004  Kanye West           14
...         ...         ...          ...
15003  Dec 2025      Davido           28
15004  Jan 2026      Davido           23
15005  Feb 2026      Davido           28
15006  Mar 2026      Davido           18
15007  Apr 2026      Davido           18

[15008 rows x 3 columns]

In [7]:
df["datetime"] = pd.to_datetime(df["datetime"], format="%b %Y")
df

        datetime     keyword  trend_index
0     2004-01-01  Kanye West            7
1     2004-02-01  Kanye West           13
2     2004-03-01  Kanye West           15
3     2004-04-01  Kanye West           15
4     2004-05-01  Kanye West           14
...          ...         ...          ...
15003 2025-12-01      Davido           28
15004 2026-01-01      Davido           23
15005 2026-02-01      Davido           28
15006 2026-03-01      Davido           18
15007 2026-04-01      Davido           18

[15008 rows x 3 columns]

In [9]:
df["keyword"].unique()

<ArrowStringArray>
[        'Kanye West',              'Drake',        'Amber Heard',
  'Cristiano Ronaldo',        'Johnny Depp',            'Beyonce',
      'Billie Eilish',   'Floyd Mayweather',       'Lionel Messi',
         'Will Smith',       'Taylor Swift',     'Olivia Rodrigo',
  'Robert Downey Jr.',      'Justin Beiber',            'Zendaya',
          'Lady Gaga',          'Bad Bunny',     'Britney Spears',
      'Stephen Curry', 'Scarlett Johansson',        'Miley Cyrus',
       'Lebron James',     'Kim Kardashian',    'Priyanka Chopra',
        'Chris Evans',                'BTS',        'Tom Holland',
     'Shah Rukh Khan',       'Stephen Chow',       'Fan Bingbing',
          'Wang Yibo',        'Jackie Chan',           'Jay Chou',
         'Jolin Tsai',              'Twice',       'Hikaru Utada',
              'AKB48',      'David Beckham',        'Emma Watson',
   'Daniel Radcliffe',     'Ayumi Hamasaki',         'Ed Sheeran',
      'Kylian Mbappe',             'Neymar',             'Jet Li',
          'BLACKPINK',              'Adele',            'Shakira',
             'Anitta',        'Salman Khan',            'Omar Sy',
             'Wizkid',          'Burna Boy',        'Hande Erçel',
  'Bright Vachirawit',             'Davido']
Length: 56, dtype: str

### Who has the highest overall average trend index in the entire dataset?

In [12]:
df.groupby("keyword").agg({"trend_index": "mean"}).sort_values(
    "trend_index", ascending=False
).head(5)

              trend_index
keyword
Twice           48.037313
Drake           33.779851
Jay Chou        29.805970
Jet Li          29.555970
Stephen Chow    29.212687

### Which celebrity reached a trend index of 100 in the very first month of the dataset (Jan 2004)?

In [19]:
df[(df["datetime"] == "2004-01-01") & (df["trend_index"] == 100)]

        datetime         keyword  trend_index
10430 2004-01-01  Ayumi Hamasaki          100

### How many unique celebrities are tracked in this dataset?

In [20]:
df["keyword"].nunique()

56

### In which year did both Amber Heard and Johnny Depp reach their peak trend index of 100?

In [23]:
df_peaks = df[df["trend_index"] == 100]
df_peaks = df_peaks[
    (df_peaks["keyword"] == "Amber Heard") | (df_peaks["keyword"] == "Johnny Depp")
]
df_peaks

       datetime      keyword  trend_index
1221 2022-05-01  Amber Heard          100
1242 2022-05-01  Johnny Depp          100

### Based on the data, who had the higher average trend index during the year 2025?

- Cristiano Ronaldo
- Lionel Messi
- Kylian Mbappe
- Lebron James

In [31]:
rivals_2022 = df[
    (df["datetime"].dt.year == 2025)
    & (
        df["keyword"].isin(
            ["Cristiano Ronaldo", "Lionel Messi", "Kylian Mbappe", "Lebron James"]
        )
    )
]
print(rivals_2022.groupby("keyword")["trend_index"].mean().sort_values(ascending=False))

keyword
Cristiano Ronaldo    23.333333
Lebron James         20.916667
Lionel Messi         10.750000
Kylian Mbappe         9.000000
Name: trend_index, dtype: float64

### What was Fan Bingbing's trend index in September 2018?

In [ ]:
df[(df["keyword"] == "Fan Bingbing") & (df["datetime"] == "2018-09-01")]

       datetime       keyword  trend_index
8216 2018-09-01  Fan Bingbing          100

### What is the most frequent (mode) value in the trend_index column?

In [53]:
df["trend_index"].mode()

0    0
Name: trend_index, dtype: int64

### Which celebrity peaked in May 2015?

In other words, which celebrity had a trend index of 100 in May 2015?

In [ ]:
peak_may_2015 = df[(df["datetime"] == "2015-05-01") & (df["trend_index"] == 100)]
peak_may_2015

        datetime      keyword  trend_index
13149 2015-05-01  Salman Khan          100

### In December 2022, which two rivals both reached a trend index of 100?

In [ ]:
df_dec_2022_peaks = df[(df["datetime"] == "2022-12-01") & (df["trend_index"] == 100)]
df_dec_2022_peaks

        datetime            keyword  trend_index
1144  2022-12-01  Cristiano Ronaldo          100
2477  2022-12-01       Lionel Messi          100
11593 2022-12-01      Kylian Mbappe          100

In [65]:
df["keyword"].unique()

<ArrowStringArray>
[        'Kanye West',              'Drake',        'Amber Heard',
  'Cristiano Ronaldo',        'Johnny Depp',            'Beyonce',
      'Billie Eilish',   'Floyd Mayweather',       'Lionel Messi',
         'Will Smith',       'Taylor Swift',     'Olivia Rodrigo',
  'Robert Downey Jr.',      'Justin Beiber',            'Zendaya',
          'Lady Gaga',          'Bad Bunny',     'Britney Spears',
      'Stephen Curry', 'Scarlett Johansson',        'Miley Cyrus',
       'Lebron James',     'Kim Kardashian',    'Priyanka Chopra',
        'Chris Evans',                'BTS',        'Tom Holland',
     'Shah Rukh Khan',       'Stephen Chow',       'Fan Bingbing',
          'Wang Yibo',        'Jackie Chan',           'Jay Chou',
         'Jolin Tsai',              'Twice',       'Hikaru Utada',
              'AKB48',      'David Beckham',        'Emma Watson',
   'Daniel Radcliffe',     'Ayumi Hamasaki',         'Ed Sheeran',
      'Kylian Mbappe',             'Neymar',             'Jet Li',
          'BLACKPINK',              'Adele',            'Shakira',
             'Anitta',        'Salman Khan',            'Omar Sy',
             'Wizkid',          'Burna Boy',        'Hande Erçel',
  'Bright Vachirawit',             'Davido']
Length: 56, dtype: str

### What was Taylor Swift's average trend index in the year 2023?

In [ ]:
ts_2023 = df[(df["keyword"] == "Taylor Swift") & (df["datetime"].dt.year == 2023)]
print(ts_2023["trend_index"].mean())

48.666666666666664

### Filter the following keywords and create a line chart that shows the trend index changes over time for the four keywords.

- Anitta
- Wizkid
- Jolin Tsai
- Ed Sheeran

Based on the line chart, which of the following explanations is most correct?

In [70]:
df_im1 = df[df["keyword"].isin(["Anitta", "Wizkid", "Jolin Tsai", "Ed Sheeran"])]
df_im1

        datetime     keyword  trend_index
8515  2004-01-01  Jolin Tsai           38
8519  2004-02-01  Jolin Tsai           41
8522  2004-03-01  Jolin Tsai           48
8526  2004-04-01  Jolin Tsai           52
8529  2004-05-01  Jolin Tsai           71
...          ...         ...          ...
14336 2025-12-01      Wizkid           41
14338 2026-01-01      Wizkid           43
14341 2026-02-01      Wizkid           33
14344 2026-03-01      Wizkid           24
14347 2026-04-01      Wizkid           27

[1072 rows x 3 columns]

In [71]:
fig = px.line(
    df_im1, x="datetime", y="trend_index", color="keyword", template="simple_white"
)
fig.show()

### Filter the following keywords and create a line chart that shows the trend index changes over time for the four keywords.

- Priyanka Chopra
- Wang Yibo
- Omar Sy
- Bright Vachirawit

Based on the line chart, which of the following explanations is incorrect?

In [ ]:
df_im2 = df[
    df["keyword"].isin(["Priyanka Chopra", "Wang Yibo", "Omar Sy", "Bright Vachirawit"])
]
df_im2

        datetime            keyword  trend_index
6055  2004-01-01    Priyanka Chopra            2
6056  2004-02-01    Priyanka Chopra            2
6059  2004-03-01    Priyanka Chopra            2
6060  2004-04-01    Priyanka Chopra            1
6062  2004-05-01    Priyanka Chopra            1
...          ...                ...          ...
14731 2025-12-01  Bright Vachirawit           12
14732 2026-01-01  Bright Vachirawit           11
14733 2026-02-01  Bright Vachirawit            9
14735 2026-03-01  Bright Vachirawit            7
14736 2026-04-01  Bright Vachirawit            6

[1072 rows x 3 columns]

In [74]:
fig = px.line(
    df_im2, x="datetime", y="trend_index", color="keyword", template="simple_white"
)
fig.show()

### Filter the following keywords and create a line chart that shows the trend index changes over time for the four keywords.

- Justin Beiber
- Bad Bunny
- Drake
- Shakira

Based on the line chart, who peaked most recently (i.e., who peaked the last)?

In [ ]:
fig = px.line(
    df[df["keyword"].isin(["Justin Beiber", "Bad Bunny", "Drake", "Shakira"])],
    x="datetime",
    y="trend_index",
    color="keyword",
    template="simple_white",
)
fig.show()

### Filter the following keywords and create a line chart that shows the trend index changes over time for the four keywords.

- Jet Li
- BLACKPINK
- BTS
- Emma Watson

Based on the line chart, who peaked the earliest (i.e., who peaked the first)?

In [83]:
fig = px.line(
    df[df["keyword"].isin(["Jet Li", "BLACKPINK", "BTS", "Emma Watson"])],
    x="datetime",
    y="trend_index",
    color="keyword",
    template="simple_white",
)
fig.show()